// app/lib/data.ts
import { Product, User } from "./types";

export const PRODUCTS: Product[] = [
  {
    id: "1",
    name: "The Black Vault",
    slug: "the-black-vault",
    price: 380,
    category: "Espresso",
    description: "Our signature double espresso — rich, bold, and unapologetically dark. Single-origin Ethiopian Yirgacheffe beans pulled at exactly 9 bars.",
    image: "https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=600&q=80",
    stock: 50,
    rating: 4.9,
    reviews: 312,
    featured: true,
    tags: ["bestseller", "strong", "espresso"],
  },
  {
    id: "2",
    name: "Velvet Latte",
    slug: "velvet-latte",
    price: 420,
    category: "Latte",
    description: "Silky steamed whole milk poured over a double shot — a texture so smooth it feels like velvet. Served hot or iced.",
    image: "https://images.unsplash.com/photo-1561882468-9110e03e0f78?w=600&q=80",
    stock: 40,
    rating: 4.8,
    reviews: 278,
    featured: true,
    tags: ["creamy", "mild", "popular"],
  },
  {
    id: "3",
    name: "Cold Brew Barrel",
    slug: "cold-brew-barrel",
    price: 460,
    category: "Cold Brew",
    description: "Steeped 24 hours in cold water for a naturally sweet, ultra-smooth brew with zero bitterness. Served over ice in a frosted glass.",
    image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=600&q=80",
    stock: 30,
    rating: 4.9,
    reviews: 198,
    featured: true,
    tags: ["cold", "smooth", "summer"],
  },
  {
    id: "4",
    name: "Caramel Vault",
    slug: "caramel-vault",
    price: 480,
    category: "Specialty",
    description: "Double espresso, steamed milk, house-made salted caramel drizzle, and a cloud of cream. Our most-ordered specialty.",
    image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=600&q=80",
    stock: 35,
    rating: 4.7,
    reviews: 421,
    featured: false,
    tags: ["sweet", "caramel", "specialty"],
  },
  {
    id: "5",
    name: "Matcha Fog",
    slug: "matcha-fog",
    price: 440,
    category: "Specialty",
    description: "Ceremonial grade matcha whisked into oat milk with a hint of vanilla. Earthy, creamy, and beautifully layered.",
    image: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=600&q=80",
    stock: 25,
    rating: 4.6,
    reviews: 143,
    featured: false,
    tags: ["matcha", "oat milk", "earthy"],
  },
  {
    id: "6",
    name: "Hazelnut Mocha",
    slug: "hazelnut-mocha",
    price: 500,
    category: "Mocha",
    description: "Dark Belgian chocolate, toasted hazelnut syrup, double espresso and airy milk foam. A dessert in a cup.",
    image: "https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=600&q=80",
    stock: 20,
    rating: 4.8,
    reviews: 267,
    featured: false,
    tags: ["chocolate", "hazelnut", "indulgent"],
  },
  {
    id: "7",
    name: "Sunrise Cappuccino",
    slug: "sunrise-cappuccino",
    price: 400,
    category: "Cappuccino",
    description: "Equal parts espresso, steamed milk and thick velvety foam. The classic Italian ratio done right — best enjoyed before noon.",
    image: "https://images.unsplash.com/photo-1534778101976-62847782c213?w=600&q=80",
    stock: 45,
    rating: 4.7,
    reviews: 189,
    featured: false,
    tags: ["classic", "foam", "morning"],
  },
  {
    id: "8",
    name: "Rose Cardamom Latte",
    slug: "rose-cardamom-latte",
    price: 520,
    category: "Specialty",
    description: "Inspired by South Asian chai culture — double espresso with rose water, freshly ground cardamom and steamed whole milk. Exotic and floral.",
    image: "https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&q=80",
    stock: 15,
    rating: 4.9,
    reviews: 97,
    featured: true,
    tags: ["rose", "cardamom", "desi fusion"],
  },
  {
    id: "9",
    name: "Single Origin Pour-Over",
    slug: "single-origin-pour-over",
    price: 550,
    category: "Filter",
    description: "Slow-dripped through a hand-held V60. We rotate origins weekly — today's is a washed Kenyan AA with notes of blackcurrant and citrus.",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
    stock: 20,
    rating: 4.9,
    reviews: 76,
    featured: false,
    tags: ["pour-over", "filter", "single origin"],
  },
];

export const CATEGORIES = ["All", "Espresso", "Latte", "Cold Brew", "Cappuccino", "Mocha", "Specialty", "Filter"];

export const DEMO_USERS: User[] = [
  { id: "u1", name: "Ali Hassan",  email: "user@coffeevault.pk",  password: "123",   role: "user" },
  { id: "u2", name: "Admin",       email: "admin@coffeevault.pk", password: "admin", role: "admin" },
];
